export const data=[
  {
    "CountryRegion": "USA",
    "Continent": "North America",
    "Population": 331198130,
    "TotalCases": 5032179,
    "NewCases": "",
    "TotalDeaths": 162804,
    "NewDeaths": "",
    "TotalRecovered": 2576668,
    "NewRecovered": "",
    "ActiveCases": 2292707,
    "SeriousCritical": 18296,
    "TotCasesPer1Mpop": 15194,
    "DeathsPer1Mpop": 492,
    "TotalTests": 63139605,
    "TestsPer1Mpop": 190640,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Brazil",
    "Continent": "South America",
    "Population": 212710692,
    "TotalCases": 2917562,
    "NewCases": "",
    "TotalDeaths": 98644,
    "NewDeaths": "",
    "TotalRecovered": 2047660,
    "NewRecovered": "",
    "ActiveCases": 771258,
    "SeriousCritical": 8318,
    "TotCasesPer1Mpop": 13716,
    "DeathsPer1Mpop": 464,
    "TotalTests": 13206188,
    "TestsPer1Mpop": 62085,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "India",
    "Continent": "Asia",
    "Population": 1381344997,
    "TotalCases": 2025409,
    "NewCases": "",
    "TotalDeaths": 41638,
    "NewDeaths": "",
    "TotalRecovered": 1377384,
    "NewRecovered": "",
    "ActiveCases": 606387,
    "SeriousCritical": 8944,
    "TotCasesPer1Mpop": 1466,
    "DeathsPer1Mpop": 30,
    "TotalTests": 22149351,
    "TestsPer1Mpop": 16035,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Russia",
    "Continent": "Europe",
    "Population": 145940924,
    "TotalCases": 871894,
    "NewCases": "",
    "TotalDeaths": 14606,
    "NewDeaths": "",
    "TotalRecovered": 676357,
    "NewRecovered": "",
    "ActiveCases": 180931,
    "SeriousCritical": 2300,
    "TotCasesPer1Mpop": 5974,
    "DeathsPer1Mpop": 100,
    "TotalTests": 29716907,
    "TestsPer1Mpop": 203623,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "South Africa",
    "Continent": "Africa",
    "Population": 59381566,
    "TotalCases": 538184,
    "NewCases": "",
    "TotalDeaths": 9604,
    "NewDeaths": "",
    "TotalRecovered": 387316,
    "NewRecovered": "",
    "ActiveCases": 141264,
    "SeriousCritical": 539,
    "TotCasesPer1Mpop": 9063,
    "DeathsPer1Mpop": 162,
    "TotalTests": 3149807,
    "TestsPer1Mpop": 53044,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Mexico",
    "Continent": "North America",
    "Population": 129066160,
    "TotalCases": 462690,
    "NewCases": 6590,
    "TotalDeaths": 50517,
    "NewDeaths": 819,
    "TotalRecovered": 308848,
    "NewRecovered": 4140,
    "ActiveCases": 103325,
    "SeriousCritical": 3987,
    "TotCasesPer1Mpop": 3585,
    "DeathsPer1Mpop": 391,
    "TotalTests": 1056915,
    "TestsPer1Mpop": 8189,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Peru",
    "Continent": "South America",
    "Population": 33016319,
    "TotalCases": 455409,
    "NewCases": "",
    "TotalDeaths": 20424,
    "NewDeaths": "",
    "TotalRecovered": 310337,
    "NewRecovered": "",
    "ActiveCases": 124648,
    "SeriousCritical": 1426,
    "TotCasesPer1Mpop": 13793,
    "DeathsPer1Mpop": 619,
    "TotalTests": 2493429,
    "TestsPer1Mpop": 75521,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Chile",
    "Continent": "South America",
    "Population": 19132514,
    "TotalCases": 366671,
    "NewCases": "",
    "TotalDeaths": 9889,
    "NewDeaths": "",
    "TotalRecovered": 340168,
    "NewRecovered": "",
    "ActiveCases": 16614,
    "SeriousCritical": 1358,
    "TotCasesPer1Mpop": 19165,
    "DeathsPer1Mpop": 517,
    "TotalTests": 1760615,
    "TestsPer1Mpop": 92022,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Colombia",
    "Continent": "South America",
    "Population": 50936262,
    "TotalCases": 357710,
    "NewCases": "",
    "TotalDeaths": 11939,
    "NewDeaths": "",
    "TotalRecovered": 192355,
    "NewRecovered": "",
    "ActiveCases": 153416,
    "SeriousCritical": 1493,
    "TotCasesPer1Mpop": 7023,
    "DeathsPer1Mpop": 234,
    "TotalTests": 1801835,
    "TestsPer1Mpop": 35374,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Spain",
    "Continent": "Europe",
    "Population": 46756648,
    "TotalCases": 354530,
    "NewCases": "",
    "TotalDeaths": 28500,
    "NewDeaths": "",
    "TotalRecovered": "",
    "NewRecovered": "",
    "ActiveCases": "",
    "SeriousCritical": 617,
    "TotCasesPer1Mpop": 7582,
    "DeathsPer1Mpop": 610,
    "TotalTests": 7064329,
    "TestsPer1Mpop": 151087,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Iran",
    "Continent": "Asia",
    "Population": 84097623,
    "TotalCases": 320117,
    "NewCases": "",
    "TotalDeaths": 17976,
    "NewDeaths": "",
    "TotalRecovered": 277463,
    "NewRecovered": "",
    "ActiveCases": 24678,
    "SeriousCritical": 4156,
    "TotCasesPer1Mpop": 3806,
    "DeathsPer1Mpop": 214,
    "TotalTests": 2612763,
    "TestsPer1Mpop": 31068,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "UK",
    "Continent": "Europe",
    "Population": 67922029,
    "TotalCases": 308134,
    "NewCases": "",
    "TotalDeaths": 46413,
    "NewDeaths": "",
    "TotalRecovered": "",
    "NewRecovered": "",
    "ActiveCases": "",
    "SeriousCritical": 73,
    "TotCasesPer1Mpop": 4537,
    "DeathsPer1Mpop": 683,
    "TotalTests": 17515234,
    "TestsPer1Mpop": 257873,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Saudi Arabia",
    "Continent": "Asia",
    "Population": 34865919,
    "TotalCases": 284226,
    "NewCases": "",
    "TotalDeaths": 3055,
    "NewDeaths": "",
    "TotalRecovered": 247089,
    "NewRecovered": "",
    "ActiveCases": 34082,
    "SeriousCritical": 1915,
    "TotCasesPer1Mpop": 8152,
    "DeathsPer1Mpop": 88,
    "TotalTests": 3635705,
    "TestsPer1Mpop": 104277,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Pakistan",
    "Continent": "Asia",
    "Population": 221295851,
    "TotalCases": 281863,
    "NewCases": "",
    "TotalDeaths": 6035,
    "NewDeaths": "",
    "TotalRecovered": 256058,
    "NewRecovered": "",
    "ActiveCases": 19770,
    "SeriousCritical": 809,
    "TotCasesPer1Mpop": 1274,
    "DeathsPer1Mpop": 27,
    "TotalTests": 2058872,
    "TestsPer1Mpop": 9304,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Bangladesh",
    "Continent": "Asia",
    "Population": 164851401,
    "TotalCases": 249651,
    "NewCases": "",
    "TotalDeaths": 3306,
    "NewDeaths": "",
    "TotalRecovered": 143824,
    "NewRecovered": "",
    "ActiveCases": 102521,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 1514,
    "DeathsPer1Mpop": 20,
    "TotalTests": 1225124,
    "TestsPer1Mpop": 7432,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Italy",
    "Continent": "Europe",
    "Population": 60452568,
    "TotalCases": 249204,
    "NewCases": "",
    "TotalDeaths": 35187,
    "NewDeaths": "",
    "TotalRecovered": 201323,
    "NewRecovered": "",
    "ActiveCases": 12694,
    "SeriousCritical": 42,
    "TotCasesPer1Mpop": 4122,
    "DeathsPer1Mpop": 582,
    "TotalTests": 7099713,
    "TestsPer1Mpop": 117443,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Turkey",
    "Continent": "Asia",
    "Population": 84428331,
    "TotalCases": 237265,
    "NewCases": "",
    "TotalDeaths": 5798,
    "NewDeaths": "",
    "TotalRecovered": 220546,
    "NewRecovered": "",
    "ActiveCases": 10921,
    "SeriousCritical": 580,
    "TotCasesPer1Mpop": 2810,
    "DeathsPer1Mpop": 69,
    "TotalTests": 5081802,
    "TestsPer1Mpop": 60191,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Argentina",
    "Continent": "South America",
    "Population": 45236884,
    "TotalCases": 228195,
    "NewCases": "",
    "TotalDeaths": 4251,
    "NewDeaths": "",
    "TotalRecovered": 99852,
    "NewRecovered": "",
    "ActiveCases": 124092,
    "SeriousCritical": 1150,
    "TotCasesPer1Mpop": 5044,
    "DeathsPer1Mpop": 94,
    "TotalTests": 794544,
    "TestsPer1Mpop": 17564,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Germany",
    "Continent": "Europe",
    "Population": 83811260,
    "TotalCases": 215210,
    "NewCases": "",
    "TotalDeaths": 9252,
    "NewDeaths": "",
    "TotalRecovered": 196200,
    "NewRecovered": "",
    "ActiveCases": 9758,
    "SeriousCritical": 236,
    "TotCasesPer1Mpop": 2568,
    "DeathsPer1Mpop": 110,
    "TotalTests": 8586648,
    "TestsPer1Mpop": 102452,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "France",
    "Continent": "Europe",
    "Population": 65288306,
    "TotalCases": 195633,
    "NewCases": "",
    "TotalDeaths": 30312,
    "NewDeaths": "",
    "TotalRecovered": 82460,
    "NewRecovered": "",
    "ActiveCases": 82861,
    "SeriousCritical": 384,
    "TotCasesPer1Mpop": 2996,
    "DeathsPer1Mpop": 464,
    "TotalTests": 3992206,
    "TestsPer1Mpop": 61147,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Iraq",
    "Continent": "Asia",
    "Population": 40306025,
    "TotalCases": 140603,
    "NewCases": "",
    "TotalDeaths": 5161,
    "NewDeaths": "",
    "TotalRecovered": 101025,
    "NewRecovered": "",
    "ActiveCases": 34417,
    "SeriousCritical": 517,
    "TotCasesPer1Mpop": 3488,
    "DeathsPer1Mpop": 128,
    "TotalTests": 1092741,
    "TestsPer1Mpop": 27111,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Philippines",
    "Continent": "Asia",
    "Population": 109722719,
    "TotalCases": 119460,
    "NewCases": "",
    "TotalDeaths": 2150,
    "NewDeaths": "",
    "TotalRecovered": 66837,
    "NewRecovered": "",
    "ActiveCases": 50473,
    "SeriousCritical": 239,
    "TotCasesPer1Mpop": 1089,
    "DeathsPer1Mpop": 20,
    "TotalTests": 1669996,
    "TestsPer1Mpop": 15220,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Indonesia",
    "Continent": "Asia",
    "Population": 273808365,
    "TotalCases": 118753,
    "NewCases": "",
    "TotalDeaths": 5521,
    "NewDeaths": "",
    "TotalRecovered": 75645,
    "NewRecovered": "",
    "ActiveCases": 37587,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 434,
    "DeathsPer1Mpop": 20,
    "TotalTests": 1633156,
    "TestsPer1Mpop": 5965,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Canada",
    "Continent": "North America",
    "Population": 37775022,
    "TotalCases": 118561,
    "NewCases": "",
    "TotalDeaths": 8966,
    "NewDeaths": "",
    "TotalRecovered": 103106,
    "NewRecovered": "",
    "ActiveCases": 6489,
    "SeriousCritical": 2263,
    "TotCasesPer1Mpop": 3139,
    "DeathsPer1Mpop": 237,
    "TotalTests": 4319172,
    "TestsPer1Mpop": 114339,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Qatar",
    "Continent": "Asia",
    "Population": 2807805,
    "TotalCases": 112092,
    "NewCases": "",
    "TotalDeaths": 178,
    "NewDeaths": "",
    "TotalRecovered": 108831,
    "NewRecovered": "",
    "ActiveCases": 3083,
    "SeriousCritical": 77,
    "TotCasesPer1Mpop": 39922,
    "DeathsPer1Mpop": 63,
    "TotalTests": 511000,
    "TestsPer1Mpop": 181993,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Kazakhstan",
    "Continent": "Asia",
    "Population": 18798667,
    "TotalCases": 95942,
    "NewCases": "",
    "TotalDeaths": 1058,
    "NewDeaths": "",
    "TotalRecovered": 68871,
    "NewRecovered": "",
    "ActiveCases": 26013,
    "SeriousCritical": 221,
    "TotCasesPer1Mpop": 5104,
    "DeathsPer1Mpop": 56,
    "TotalTests": 2163713,
    "TestsPer1Mpop": 115099,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Egypt",
    "Continent": "Africa",
    "Population": 102516525,
    "TotalCases": 95006,
    "NewCases": "",
    "TotalDeaths": 4951,
    "NewDeaths": "",
    "TotalRecovered": 48898,
    "NewRecovered": "",
    "ActiveCases": 41157,
    "SeriousCritical": 41,
    "TotCasesPer1Mpop": 927,
    "DeathsPer1Mpop": 48,
    "TotalTests": 135000,
    "TestsPer1Mpop": 1317,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Ecuador",
    "Continent": "South America",
    "Population": 17668824,
    "TotalCases": 90537,
    "NewCases": "",
    "TotalDeaths": 5877,
    "NewDeaths": "",
    "TotalRecovered": 71318,
    "NewRecovered": "",
    "ActiveCases": 13342,
    "SeriousCritical": 378,
    "TotCasesPer1Mpop": 5124,
    "DeathsPer1Mpop": 333,
    "TotalTests": 258582,
    "TestsPer1Mpop": 14635,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Bolivia",
    "Continent": "South America",
    "Population": 11688459,
    "TotalCases": 86423,
    "NewCases": 1282,
    "TotalDeaths": 3465,
    "NewDeaths": 80,
    "TotalRecovered": 27373,
    "NewRecovered": 936,
    "ActiveCases": 55585,
    "SeriousCritical": 71,
    "TotCasesPer1Mpop": 7394,
    "DeathsPer1Mpop": 296,
    "TotalTests": 183583,
    "TestsPer1Mpop": 15706,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Sweden",
    "Continent": "Europe",
    "Population": 10105596,
    "TotalCases": 81967,
    "NewCases": "",
    "TotalDeaths": 5766,
    "NewDeaths": "",
    "TotalRecovered": "",
    "NewRecovered": "",
    "ActiveCases": "",
    "SeriousCritical": 38,
    "TotCasesPer1Mpop": 8111,
    "DeathsPer1Mpop": 571,
    "TotalTests": 863315,
    "TestsPer1Mpop": 85429,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Oman",
    "Continent": "Asia",
    "Population": 5118446,
    "TotalCases": 80713,
    "NewCases": "",
    "TotalDeaths": 492,
    "NewDeaths": "",
    "TotalRecovered": 70910,
    "NewRecovered": "",
    "ActiveCases": 9311,
    "SeriousCritical": 177,
    "TotCasesPer1Mpop": 15769,
    "DeathsPer1Mpop": 96,
    "TotalTests": 309212,
    "TestsPer1Mpop": 60411,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Israel",
    "Continent": "Asia",
    "Population": 9197590,
    "TotalCases": 79559,
    "NewCases": "",
    "TotalDeaths": 576,
    "NewDeaths": "",
    "TotalRecovered": 53427,
    "NewRecovered": "",
    "ActiveCases": 25556,
    "SeriousCritical": 358,
    "TotCasesPer1Mpop": 8650,
    "DeathsPer1Mpop": 63,
    "TotalTests": 1872453,
    "TestsPer1Mpop": 203581,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Ukraine",
    "Continent": "Europe",
    "Population": 43705858,
    "TotalCases": 76808,
    "NewCases": "",
    "TotalDeaths": 1819,
    "NewDeaths": "",
    "TotalRecovered": 42524,
    "NewRecovered": "",
    "ActiveCases": 32465,
    "SeriousCritical": 158,
    "TotCasesPer1Mpop": 1757,
    "DeathsPer1Mpop": 42,
    "TotalTests": 1116641,
    "TestsPer1Mpop": 25549,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Dominican Republic",
    "Continent": "North America",
    "Population": 10858648,
    "TotalCases": 76536,
    "NewCases": "",
    "TotalDeaths": 1246,
    "NewDeaths": "",
    "TotalRecovered": 40539,
    "NewRecovered": "",
    "ActiveCases": 34751,
    "SeriousCritical": 317,
    "TotCasesPer1Mpop": 7048,
    "DeathsPer1Mpop": 115,
    "TotalTests": 281926,
    "TestsPer1Mpop": 25963,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Panama",
    "Continent": "North America",
    "Population": 4321282,
    "TotalCases": 71418,
    "NewCases": "",
    "TotalDeaths": 1574,
    "NewDeaths": "",
    "TotalRecovered": 45658,
    "NewRecovered": "",
    "ActiveCases": 24186,
    "SeriousCritical": 161,
    "TotCasesPer1Mpop": 16527,
    "DeathsPer1Mpop": 364,
    "TotalTests": 240995,
    "TestsPer1Mpop": 55769,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Belgium",
    "Continent": "Europe",
    "Population": 11594739,
    "TotalCases": 71158,
    "NewCases": "",
    "TotalDeaths": 9859,
    "NewDeaths": "",
    "TotalRecovered": 17661,
    "NewRecovered": "",
    "ActiveCases": 43638,
    "SeriousCritical": 61,
    "TotCasesPer1Mpop": 6137,
    "DeathsPer1Mpop": 850,
    "TotalTests": 1767120,
    "TestsPer1Mpop": 152407,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Kuwait",
    "Continent": "Asia",
    "Population": 4276658,
    "TotalCases": 70045,
    "NewCases": "",
    "TotalDeaths": 469,
    "NewDeaths": "",
    "TotalRecovered": 61610,
    "NewRecovered": "",
    "ActiveCases": 7966,
    "SeriousCritical": 127,
    "TotCasesPer1Mpop": 16378,
    "DeathsPer1Mpop": 110,
    "TotalTests": 522200,
    "TestsPer1Mpop": 122105,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Belarus",
    "Continent": "Europe",
    "Population": 9449001,
    "TotalCases": 68503,
    "NewCases": "",
    "TotalDeaths": 580,
    "NewDeaths": "",
    "TotalRecovered": 63756,
    "NewRecovered": "",
    "ActiveCases": 4167,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 7250,
    "DeathsPer1Mpop": 61,
    "TotalTests": 1344303,
    "TestsPer1Mpop": 142269,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "UAE",
    "Continent": "Asia",
    "Population": 9902079,
    "TotalCases": 61845,
    "NewCases": "",
    "TotalDeaths": 354,
    "NewDeaths": "",
    "TotalRecovered": 55739,
    "NewRecovered": "",
    "ActiveCases": 5752,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 6246,
    "DeathsPer1Mpop": 36,
    "TotalTests": 5262658,
    "TestsPer1Mpop": 531470,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Romania",
    "Continent": "Europe",
    "Population": 19224023,
    "TotalCases": 57895,
    "NewCases": "",
    "TotalDeaths": 2566,
    "NewDeaths": "",
    "TotalRecovered": 28992,
    "NewRecovered": "",
    "ActiveCases": 26337,
    "SeriousCritical": 458,
    "TotCasesPer1Mpop": 3012,
    "DeathsPer1Mpop": 133,
    "TotalTests": 1319369,
    "TestsPer1Mpop": 68631,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Netherlands",
    "Continent": "Europe",
    "Population": 17138756,
    "TotalCases": 56982,
    "NewCases": "",
    "TotalDeaths": 6153,
    "NewDeaths": "",
    "TotalRecovered": "",
    "NewRecovered": "",
    "ActiveCases": "",
    "SeriousCritical": 37,
    "TotCasesPer1Mpop": 3325,
    "DeathsPer1Mpop": 359,
    "TotalTests": 1079860,
    "TestsPer1Mpop": 63007,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Singapore",
    "Continent": "Asia",
    "Population": 5854932,
    "TotalCases": 54555,
    "NewCases": "",
    "TotalDeaths": 27,
    "NewDeaths": "",
    "TotalRecovered": 48031,
    "NewRecovered": "",
    "ActiveCases": 6497,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 9318,
    "DeathsPer1Mpop": 5,
    "TotalTests": 1474372,
    "TestsPer1Mpop": 251817,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Guatemala",
    "Continent": "North America",
    "Population": 17946899,
    "TotalCases": 54339,
    "NewCases": "",
    "TotalDeaths": 2119,
    "NewDeaths": "",
    "TotalRecovered": 42070,
    "NewRecovered": "",
    "ActiveCases": 10150,
    "SeriousCritical": 5,
    "TotCasesPer1Mpop": 3028,
    "DeathsPer1Mpop": 118,
    "TotalTests": 172712,
    "TestsPer1Mpop": 9624,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Portugal",
    "Continent": "Europe",
    "Population": 10193593,
    "TotalCases": 52061,
    "NewCases": "",
    "TotalDeaths": 1743,
    "NewDeaths": "",
    "TotalRecovered": 37840,
    "NewRecovered": "",
    "ActiveCases": 12478,
    "SeriousCritical": 42,
    "TotCasesPer1Mpop": 5107,
    "DeathsPer1Mpop": 171,
    "TotalTests": 1705474,
    "TestsPer1Mpop": 167308,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Poland",
    "Continent": "Europe",
    "Population": 37842302,
    "TotalCases": 49515,
    "NewCases": "",
    "TotalDeaths": 1774,
    "NewDeaths": "",
    "TotalRecovered": 35642,
    "NewRecovered": "",
    "ActiveCases": 12099,
    "SeriousCritical": 72,
    "TotCasesPer1Mpop": 1308,
    "DeathsPer1Mpop": 47,
    "TotalTests": 2374686,
    "TestsPer1Mpop": 62752,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Nigeria",
    "Continent": "Africa",
    "Population": 206606300,
    "TotalCases": 45244,
    "NewCases": "",
    "TotalDeaths": 930,
    "NewDeaths": "",
    "TotalRecovered": 32430,
    "NewRecovered": "",
    "ActiveCases": 11884,
    "SeriousCritical": 7,
    "TotCasesPer1Mpop": 219,
    "DeathsPer1Mpop": 5,
    "TotalTests": 306894,
    "TestsPer1Mpop": 1485,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Honduras",
    "Continent": "North America",
    "Population": 9919704,
    "TotalCases": 45098,
    "NewCases": "",
    "TotalDeaths": 1423,
    "NewDeaths": "",
    "TotalRecovered": 6116,
    "NewRecovered": "",
    "ActiveCases": 37559,
    "SeriousCritical": 52,
    "TotCasesPer1Mpop": 4546,
    "DeathsPer1Mpop": 143,
    "TotalTests": 109292,
    "TestsPer1Mpop": 11018,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Bahrain",
    "Continent": "Asia",
    "Population": 1706669,
    "TotalCases": 42889,
    "NewCases": "",
    "TotalDeaths": 156,
    "NewDeaths": "",
    "TotalRecovered": 39945,
    "NewRecovered": "",
    "ActiveCases": 2788,
    "SeriousCritical": 41,
    "TotCasesPer1Mpop": 25130,
    "DeathsPer1Mpop": 91,
    "TotalTests": 876700,
    "TestsPer1Mpop": 513691,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Japan",
    "Continent": "Asia",
    "Population": 126435859,
    "TotalCases": 42263,
    "NewCases": "",
    "TotalDeaths": 1026,
    "NewDeaths": "",
    "TotalRecovered": 28877,
    "NewRecovered": "",
    "ActiveCases": 12360,
    "SeriousCritical": 115,
    "TotCasesPer1Mpop": 334,
    "DeathsPer1Mpop": 8,
    "TotalTests": 938739,
    "TestsPer1Mpop": 7425,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Armenia",
    "Continent": "Asia",
    "Population": 2963811,
    "TotalCases": 39819,
    "NewCases": "",
    "TotalDeaths": 772,
    "NewDeaths": "",
    "TotalRecovered": 31556,
    "NewRecovered": "",
    "ActiveCases": 7491,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 13435,
    "DeathsPer1Mpop": 260,
    "TotalTests": 171600,
    "TestsPer1Mpop": 57898,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Ghana",
    "Continent": "Africa",
    "Population": 31133483,
    "TotalCases": 39642,
    "NewCases": "",
    "TotalDeaths": 199,
    "NewDeaths": "",
    "TotalRecovered": 36384,
    "NewRecovered": "",
    "ActiveCases": 3059,
    "SeriousCritical": 7,
    "TotCasesPer1Mpop": 1273,
    "DeathsPer1Mpop": 6,
    "TotalTests": 405817,
    "TestsPer1Mpop": 13035,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Kyrgyzstan",
    "Continent": "Asia",
    "Population": 6534479,
    "TotalCases": 38659,
    "NewCases": "",
    "TotalDeaths": 1447,
    "NewDeaths": "",
    "TotalRecovered": 30099,
    "NewRecovered": "",
    "ActiveCases": 7113,
    "SeriousCritical": 24,
    "TotCasesPer1Mpop": 5916,
    "DeathsPer1Mpop": 221,
    "TotalTests": 267718,
    "TestsPer1Mpop": 40970,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Afghanistan",
    "Continent": "Asia",
    "Population": 39009447,
    "TotalCases": 36896,
    "NewCases": "",
    "TotalDeaths": 1298,
    "NewDeaths": "",
    "TotalRecovered": 25840,
    "NewRecovered": "",
    "ActiveCases": 9758,
    "SeriousCritical": 31,
    "TotCasesPer1Mpop": 946,
    "DeathsPer1Mpop": 33,
    "TotalTests": 90396,
    "TestsPer1Mpop": 2317,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Switzerland",
    "Continent": "Europe",
    "Population": 8660952,
    "TotalCases": 36108,
    "NewCases": "",
    "TotalDeaths": 1985,
    "NewDeaths": "",
    "TotalRecovered": 31600,
    "NewRecovered": "",
    "ActiveCases": 2523,
    "SeriousCritical": 23,
    "TotCasesPer1Mpop": 4169,
    "DeathsPer1Mpop": 229,
    "TotalTests": 822764,
    "TestsPer1Mpop": 94997,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Algeria",
    "Continent": "Africa",
    "Population": 43926079,
    "TotalCases": 33626,
    "NewCases": "",
    "TotalDeaths": 1273,
    "NewDeaths": "",
    "TotalRecovered": 23238,
    "NewRecovered": "",
    "ActiveCases": 9115,
    "SeriousCritical": 57,
    "TotCasesPer1Mpop": 766,
    "DeathsPer1Mpop": 29,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Azerbaijan",
    "Continent": "Asia",
    "Population": 10148243,
    "TotalCases": 33247,
    "NewCases": "",
    "TotalDeaths": 479,
    "NewDeaths": "",
    "TotalRecovered": 29275,
    "NewRecovered": "",
    "ActiveCases": 3493,
    "SeriousCritical": 66,
    "TotCasesPer1Mpop": 3276,
    "DeathsPer1Mpop": 47,
    "TotalTests": 766179,
    "TestsPer1Mpop": 75499,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Morocco",
    "Continent": "Africa",
    "Population": 36953359,
    "TotalCases": 29644,
    "NewCases": "",
    "TotalDeaths": 449,
    "NewDeaths": "",
    "TotalRecovered": 20553,
    "NewRecovered": "",
    "ActiveCases": 8642,
    "SeriousCritical": 31,
    "TotCasesPer1Mpop": 802,
    "DeathsPer1Mpop": 12,
    "TotalTests": 1383816,
    "TestsPer1Mpop": 37448,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Uzbekistan",
    "Continent": "Asia",
    "Population": 33516027,
    "TotalCases": 28315,
    "NewCases": "",
    "TotalDeaths": 175,
    "NewDeaths": "",
    "TotalRecovered": 19291,
    "NewRecovered": "",
    "ActiveCases": 8849,
    "SeriousCritical": 228,
    "TotCasesPer1Mpop": 845,
    "DeathsPer1Mpop": 5,
    "TotalTests": 1377915,
    "TestsPer1Mpop": 41112,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Serbia",
    "Continent": "Europe",
    "Population": 8733665,
    "TotalCases": 27332,
    "NewCases": "",
    "TotalDeaths": 621,
    "NewDeaths": "",
    "TotalRecovered": 14047,
    "NewRecovered": "",
    "ActiveCases": 12664,
    "SeriousCritical": 120,
    "TotCasesPer1Mpop": 3129,
    "DeathsPer1Mpop": 71,
    "TotalTests": 723137,
    "TestsPer1Mpop": 82799,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Moldova",
    "Continent": "Europe",
    "Population": 4032983,
    "TotalCases": 26628,
    "NewCases": "",
    "TotalDeaths": 828,
    "NewDeaths": "",
    "TotalRecovered": 18676,
    "NewRecovered": "",
    "ActiveCases": 7124,
    "SeriousCritical": 362,
    "TotCasesPer1Mpop": 6603,
    "DeathsPer1Mpop": 205,
    "TotalTests": 128076,
    "TestsPer1Mpop": 31757,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Ireland",
    "Continent": "Europe",
    "Population": 4943200,
    "TotalCases": 26372,
    "NewCases": "",
    "TotalDeaths": 1768,
    "NewDeaths": "",
    "TotalRecovered": 23364,
    "NewRecovered": "",
    "ActiveCases": 1240,
    "SeriousCritical": 5,
    "TotCasesPer1Mpop": 5335,
    "DeathsPer1Mpop": 358,
    "TotalTests": 652917,
    "TestsPer1Mpop": 132084,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Kenya",
    "Continent": "Africa",
    "Population": 53881160,
    "TotalCases": 24411,
    "NewCases": "",
    "TotalDeaths": 399,
    "NewDeaths": "",
    "TotalRecovered": 10444,
    "NewRecovered": "",
    "ActiveCases": 13568,
    "SeriousCritical": 44,
    "TotCasesPer1Mpop": 453,
    "DeathsPer1Mpop": 7,
    "TotalTests": 335318,
    "TestsPer1Mpop": 6223,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Venezuela",
    "Continent": "South America",
    "Population": 28427499,
    "TotalCases": 22299,
    "NewCases": "",
    "TotalDeaths": 195,
    "NewDeaths": "",
    "TotalRecovered": 12146,
    "NewRecovered": "",
    "ActiveCases": 9958,
    "SeriousCritical": 42,
    "TotCasesPer1Mpop": 784,
    "DeathsPer1Mpop": 7,
    "TotalTests": 1567431,
    "TestsPer1Mpop": 55138,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Nepal",
    "Continent": "Asia",
    "Population": 29186486,
    "TotalCases": 21750,
    "NewCases": "",
    "TotalDeaths": 65,
    "NewDeaths": "",
    "TotalRecovered": 15389,
    "NewRecovered": "",
    "ActiveCases": 6296,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 745,
    "DeathsPer1Mpop": 2,
    "TotalTests": 731977,
    "TestsPer1Mpop": 25079,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Austria",
    "Continent": "Europe",
    "Population": 9011577,
    "TotalCases": 21696,
    "NewCases": "",
    "TotalDeaths": 719,
    "NewDeaths": "",
    "TotalRecovered": 19596,
    "NewRecovered": "",
    "ActiveCases": 1381,
    "SeriousCritical": 25,
    "TotCasesPer1Mpop": 2408,
    "DeathsPer1Mpop": 80,
    "TotalTests": 937275,
    "TestsPer1Mpop": 104008,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Costa Rica",
    "Continent": "North America",
    "Population": 5098730,
    "TotalCases": 21070,
    "NewCases": "",
    "TotalDeaths": 200,
    "NewDeaths": "",
    "TotalRecovered": 7038,
    "NewRecovered": "",
    "ActiveCases": 13832,
    "SeriousCritical": 103,
    "TotCasesPer1Mpop": 4132,
    "DeathsPer1Mpop": 39,
    "TotalTests": 96110,
    "TestsPer1Mpop": 18850,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Ethiopia",
    "Continent": "Africa",
    "Population": 115223736,
    "TotalCases": 20900,
    "NewCases": "",
    "TotalDeaths": 365,
    "NewDeaths": "",
    "TotalRecovered": 9027,
    "NewRecovered": "",
    "ActiveCases": 11508,
    "SeriousCritical": 185,
    "TotCasesPer1Mpop": 181,
    "DeathsPer1Mpop": 3,
    "TotalTests": 468814,
    "TestsPer1Mpop": 4069,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Australia",
    "Continent": "Australia/Oceania",
    "Population": 25528864,
    "TotalCases": 19890,
    "NewCases": "",
    "TotalDeaths": 255,
    "NewDeaths": "",
    "TotalRecovered": 10941,
    "NewRecovered": "",
    "ActiveCases": 8694,
    "SeriousCritical": 52,
    "TotCasesPer1Mpop": 779,
    "DeathsPer1Mpop": 10,
    "TotalTests": 4631419,
    "TestsPer1Mpop": 181419,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "El Salvador",
    "Continent": "North America",
    "Population": 6489514,
    "TotalCases": 19126,
    "NewCases": "",
    "TotalDeaths": 513,
    "NewDeaths": "",
    "TotalRecovered": 9236,
    "NewRecovered": "",
    "ActiveCases": 9377,
    "SeriousCritical": 509,
    "TotCasesPer1Mpop": 2947,
    "DeathsPer1Mpop": 79,
    "TotalTests": 251271,
    "TestsPer1Mpop": 38720,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Czechia",
    "Continent": "Europe",
    "Population": 10711019,
    "TotalCases": 17731,
    "NewCases": "",
    "TotalDeaths": 390,
    "NewDeaths": "",
    "TotalRecovered": 12320,
    "NewRecovered": "",
    "ActiveCases": 5021,
    "SeriousCritical": 17,
    "TotCasesPer1Mpop": 1655,
    "DeathsPer1Mpop": 36,
    "TotalTests": 728670,
    "TestsPer1Mpop": 68030,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Cameroon",
    "Continent": "Africa",
    "Population": 26606188,
    "TotalCases": 17718,
    "NewCases": "",
    "TotalDeaths": 391,
    "NewDeaths": "",
    "TotalRecovered": 15320,
    "NewRecovered": "",
    "ActiveCases": 2007,
    "SeriousCritical": 30,
    "TotCasesPer1Mpop": 666,
    "DeathsPer1Mpop": 15,
    "TotalTests": 149000,
    "TestsPer1Mpop": 5600,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Ivory Coast",
    "Continent": "Africa",
    "Population": 26437950,
    "TotalCases": 16447,
    "NewCases": "",
    "TotalDeaths": 103,
    "NewDeaths": "",
    "TotalRecovered": 12484,
    "NewRecovered": "",
    "ActiveCases": 3860,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 622,
    "DeathsPer1Mpop": 4,
    "TotalTests": 104584,
    "TestsPer1Mpop": 3956,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "S. Korea",
    "Continent": "Asia",
    "Population": 51273732,
    "TotalCases": 14519,
    "NewCases": 20,
    "TotalDeaths": 303,
    "NewDeaths": 1,
    "TotalRecovered": 13543,
    "NewRecovered": 42,
    "ActiveCases": 673,
    "SeriousCritical": 18,
    "TotCasesPer1Mpop": 283,
    "DeathsPer1Mpop": 6,
    "TotalTests": 1613652,
    "TestsPer1Mpop": 31471,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Denmark",
    "Continent": "Europe",
    "Population": 5794279,
    "TotalCases": 14306,
    "NewCases": "",
    "TotalDeaths": 617,
    "NewDeaths": "",
    "TotalRecovered": 12787,
    "NewRecovered": "",
    "ActiveCases": 902,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 2469,
    "DeathsPer1Mpop": 106,
    "TotalTests": 1654512,
    "TestsPer1Mpop": 285542,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Palestine",
    "Continent": "Asia",
    "Population": 5112340,
    "TotalCases": 13398,
    "NewCases": "",
    "TotalDeaths": 92,
    "NewDeaths": "",
    "TotalRecovered": 6907,
    "NewRecovered": "",
    "ActiveCases": 6399,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 2621,
    "DeathsPer1Mpop": 18,
    "TotalTests": 200280,
    "TestsPer1Mpop": 39176,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Bosnia and Herzegovina",
    "Continent": "Europe",
    "Population": 3278650,
    "TotalCases": 13396,
    "NewCases": "",
    "TotalDeaths": 384,
    "NewDeaths": "",
    "TotalRecovered": 7042,
    "NewRecovered": "",
    "ActiveCases": 5970,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 4086,
    "DeathsPer1Mpop": 117,
    "TotalTests": 147021,
    "TestsPer1Mpop": 44842,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Bulgaria",
    "Continent": "Europe",
    "Population": 6942854,
    "TotalCases": 13014,
    "NewCases": "",
    "TotalDeaths": 435,
    "NewDeaths": "",
    "TotalRecovered": 7374,
    "NewRecovered": "",
    "ActiveCases": 5205,
    "SeriousCritical": 47,
    "TotCasesPer1Mpop": 1874,
    "DeathsPer1Mpop": 63,
    "TotalTests": 294087,
    "TestsPer1Mpop": 42358,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Madagascar",
    "Continent": "Africa",
    "Population": 27755708,
    "TotalCases": 12526,
    "NewCases": "",
    "TotalDeaths": 134,
    "NewDeaths": "",
    "TotalRecovered": 10148,
    "NewRecovered": "",
    "ActiveCases": 2244,
    "SeriousCritical": 88,
    "TotCasesPer1Mpop": 451,
    "DeathsPer1Mpop": 5,
    "TotalTests": 46301,
    "TestsPer1Mpop": 1668,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Sudan",
    "Continent": "Africa",
    "Population": 43943536,
    "TotalCases": 11780,
    "NewCases": "",
    "TotalDeaths": 763,
    "NewDeaths": "",
    "TotalRecovered": 6194,
    "NewRecovered": "",
    "ActiveCases": 4823,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 268,
    "DeathsPer1Mpop": 17,
    "TotalTests": 401,
    "TestsPer1Mpop": 9,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "North Macedonia",
    "Continent": "Europe",
    "Population": 2083365,
    "TotalCases": 11399,
    "NewCases": "",
    "TotalDeaths": 517,
    "NewDeaths": "",
    "TotalRecovered": 7480,
    "NewRecovered": "",
    "ActiveCases": 3402,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 5471,
    "DeathsPer1Mpop": 248,
    "TotalTests": 109946,
    "TestsPer1Mpop": 52773,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Senegal",
    "Continent": "Africa",
    "Population": 16783877,
    "TotalCases": 10715,
    "NewCases": "",
    "TotalDeaths": 223,
    "NewDeaths": "",
    "TotalRecovered": 7101,
    "NewRecovered": "",
    "ActiveCases": 3391,
    "SeriousCritical": 33,
    "TotCasesPer1Mpop": 638,
    "DeathsPer1Mpop": 13,
    "TotalTests": 114761,
    "TestsPer1Mpop": 6838,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Norway",
    "Continent": "Europe",
    "Population": 5425471,
    "TotalCases": 9468,
    "NewCases": "",
    "TotalDeaths": 256,
    "NewDeaths": "",
    "TotalRecovered": 8857,
    "NewRecovered": "",
    "ActiveCases": 355,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 1745,
    "DeathsPer1Mpop": 47,
    "TotalTests": 472841,
    "TestsPer1Mpop": 87152,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "DRC",
    "Continent": "Africa",
    "Population": 89802183,
    "TotalCases": 9309,
    "NewCases": "",
    "TotalDeaths": 215,
    "NewDeaths": "",
    "TotalRecovered": 8048,
    "NewRecovered": "",
    "ActiveCases": 1046,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 104,
    "DeathsPer1Mpop": 2,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Malaysia",
    "Continent": "Asia",
    "Population": 32406372,
    "TotalCases": 9038,
    "NewCases": "",
    "TotalDeaths": 125,
    "NewDeaths": "",
    "TotalRecovered": 8713,
    "NewRecovered": "",
    "ActiveCases": 200,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 279,
    "DeathsPer1Mpop": 4,
    "TotalTests": 991333,
    "TestsPer1Mpop": 30591,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "French Guiana",
    "Continent": "South America",
    "Population": 299385,
    "TotalCases": 8127,
    "NewCases": "",
    "TotalDeaths": 47,
    "NewDeaths": "",
    "TotalRecovered": 7240,
    "NewRecovered": "",
    "ActiveCases": 840,
    "SeriousCritical": 23,
    "TotCasesPer1Mpop": 27146,
    "DeathsPer1Mpop": 157,
    "TotalTests": 41412,
    "TestsPer1Mpop": 138324,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Gabon",
    "Continent": "Africa",
    "Population": 2230563,
    "TotalCases": 7787,
    "NewCases": "",
    "TotalDeaths": 51,
    "NewDeaths": "",
    "TotalRecovered": 5609,
    "NewRecovered": "",
    "ActiveCases": 2127,
    "SeriousCritical": 11,
    "TotCasesPer1Mpop": 3491,
    "DeathsPer1Mpop": 23,
    "TotalTests": 85369,
    "TestsPer1Mpop": 38272,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Tajikistan",
    "Continent": "Asia",
    "Population": 9557468,
    "TotalCases": 7665,
    "NewCases": "",
    "TotalDeaths": 62,
    "NewDeaths": "",
    "TotalRecovered": 6443,
    "NewRecovered": "",
    "ActiveCases": 1160,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 802,
    "DeathsPer1Mpop": 6,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Guinea",
    "Continent": "Africa",
    "Population": 13164905,
    "TotalCases": 7664,
    "NewCases": "",
    "TotalDeaths": 49,
    "NewDeaths": "",
    "TotalRecovered": 6757,
    "NewRecovered": "",
    "ActiveCases": 858,
    "SeriousCritical": 24,
    "TotCasesPer1Mpop": 582,
    "DeathsPer1Mpop": 4,
    "TotalTests": 14407,
    "TestsPer1Mpop": 1094,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Haiti",
    "Continent": "North America",
    "Population": 11416103,
    "TotalCases": 7544,
    "NewCases": "",
    "TotalDeaths": 171,
    "NewDeaths": "",
    "TotalRecovered": 4832,
    "NewRecovered": "",
    "ActiveCases": 2541,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 661,
    "DeathsPer1Mpop": 15,
    "TotalTests": 18443,
    "TestsPer1Mpop": 1616,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Finland",
    "Continent": "Europe",
    "Population": 5541604,
    "TotalCases": 7532,
    "NewCases": "",
    "TotalDeaths": 331,
    "NewDeaths": "",
    "TotalRecovered": 6980,
    "NewRecovered": "",
    "ActiveCases": 221,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 1359,
    "DeathsPer1Mpop": 60,
    "TotalTests": 389500,
    "TestsPer1Mpop": 70287,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Zambia",
    "Continent": "Africa",
    "Population": 18430129,
    "TotalCases": 7164,
    "NewCases": "",
    "TotalDeaths": 199,
    "NewDeaths": "",
    "TotalRecovered": 5786,
    "NewRecovered": "",
    "ActiveCases": 1179,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 389,
    "DeathsPer1Mpop": 11,
    "TotalTests": 90307,
    "TestsPer1Mpop": 4900,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Luxembourg",
    "Continent": "Europe",
    "Population": 626952,
    "TotalCases": 7073,
    "NewCases": "",
    "TotalDeaths": 119,
    "NewDeaths": "",
    "TotalRecovered": 5750,
    "NewRecovered": "",
    "ActiveCases": 1204,
    "SeriousCritical": 9,
    "TotCasesPer1Mpop": 11282,
    "DeathsPer1Mpop": 190,
    "TotalTests": 623994,
    "TestsPer1Mpop": 995282,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Mauritania",
    "Continent": "Africa",
    "Population": 4660728,
    "TotalCases": 6444,
    "NewCases": "",
    "TotalDeaths": 157,
    "NewDeaths": "",
    "TotalRecovered": 5291,
    "NewRecovered": "",
    "ActiveCases": 996,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 1383,
    "DeathsPer1Mpop": 34,
    "TotalTests": 57387,
    "TestsPer1Mpop": 12313,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Paraguay",
    "Continent": "South America",
    "Population": 7141091,
    "TotalCases": 6375,
    "NewCases": "",
    "TotalDeaths": 66,
    "NewDeaths": "",
    "TotalRecovered": 4974,
    "NewRecovered": "",
    "ActiveCases": 1335,
    "SeriousCritical": 23,
    "TotCasesPer1Mpop": 893,
    "DeathsPer1Mpop": 9,
    "TotalTests": 135277,
    "TestsPer1Mpop": 18943,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Albania",
    "Continent": "Europe",
    "Population": 2877470,
    "TotalCases": 6016,
    "NewCases": "",
    "TotalDeaths": 188,
    "NewDeaths": "",
    "TotalRecovered": 3155,
    "NewRecovered": "",
    "ActiveCases": 2673,
    "SeriousCritical": 23,
    "TotCasesPer1Mpop": 2091,
    "DeathsPer1Mpop": 65,
    "TotalTests": 38997,
    "TestsPer1Mpop": 13553,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Lebanon",
    "Continent": "Asia",
    "Population": 6822220,
    "TotalCases": 5672,
    "NewCases": "",
    "TotalDeaths": 70,
    "NewDeaths": "",
    "TotalRecovered": 1974,
    "NewRecovered": "",
    "ActiveCases": 3628,
    "SeriousCritical": 46,
    "TotCasesPer1Mpop": 831,
    "DeathsPer1Mpop": 10,
    "TotalTests": 345268,
    "TestsPer1Mpop": 50609,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Croatia",
    "Continent": "Europe",
    "Population": 4102577,
    "TotalCases": 5404,
    "NewCases": "",
    "TotalDeaths": 155,
    "NewDeaths": "",
    "TotalRecovered": 4688,
    "NewRecovered": "",
    "ActiveCases": 561,
    "SeriousCritical": 7,
    "TotCasesPer1Mpop": 1317,
    "DeathsPer1Mpop": 38,
    "TotalTests": 125317,
    "TestsPer1Mpop": 30546,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Djibouti",
    "Continent": "Africa",
    "Population": 989387,
    "TotalCases": 5330,
    "NewCases": "",
    "TotalDeaths": 59,
    "NewDeaths": "",
    "TotalRecovered": 5057,
    "NewRecovered": "",
    "ActiveCases": 214,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 5387,
    "DeathsPer1Mpop": 60,
    "TotalTests": 59909,
    "TestsPer1Mpop": 60552,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Greece",
    "Continent": "Europe",
    "Population": 10417673,
    "TotalCases": 5123,
    "NewCases": "",
    "TotalDeaths": 210,
    "NewDeaths": "",
    "TotalRecovered": 1374,
    "NewRecovered": "",
    "ActiveCases": 3539,
    "SeriousCritical": 14,
    "TotCasesPer1Mpop": 492,
    "DeathsPer1Mpop": 20,
    "TotalTests": 619393,
    "TestsPer1Mpop": 59456,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Libya",
    "Continent": "Africa",
    "Population": 6880353,
    "TotalCases": 4879,
    "NewCases": "",
    "TotalDeaths": 107,
    "NewDeaths": "",
    "TotalRecovered": 652,
    "NewRecovered": "",
    "ActiveCases": 4120,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 709,
    "DeathsPer1Mpop": 16,
    "TotalTests": 59699,
    "TestsPer1Mpop": 8677,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Equatorial Guinea",
    "Continent": "Africa",
    "Population": 1407001,
    "TotalCases": 4821,
    "NewCases": "",
    "TotalDeaths": 83,
    "NewDeaths": "",
    "TotalRecovered": 2182,
    "NewRecovered": "",
    "ActiveCases": 2556,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3426,
    "DeathsPer1Mpop": 59,
    "TotalTests": 44356,
    "TestsPer1Mpop": 31525,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Maldives",
    "Continent": "Asia",
    "Population": 541448,
    "TotalCases": 4680,
    "NewCases": "",
    "TotalDeaths": 19,
    "NewDeaths": "",
    "TotalRecovered": 2725,
    "NewRecovered": "",
    "ActiveCases": 1936,
    "SeriousCritical": 12,
    "TotCasesPer1Mpop": 8643,
    "DeathsPer1Mpop": 35,
    "TotalTests": 85587,
    "TestsPer1Mpop": 158071,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "CAR",
    "Continent": "Africa",
    "Population": 4837752,
    "TotalCases": 4620,
    "NewCases": "",
    "TotalDeaths": 59,
    "NewDeaths": "",
    "TotalRecovered": 1641,
    "NewRecovered": "",
    "ActiveCases": 2920,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 955,
    "DeathsPer1Mpop": 12,
    "TotalTests": 29589,
    "TestsPer1Mpop": 6116,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Hungary",
    "Continent": "Europe",
    "Population": 9657785,
    "TotalCases": 4597,
    "NewCases": "",
    "TotalDeaths": 600,
    "NewDeaths": "",
    "TotalRecovered": 3463,
    "NewRecovered": "",
    "ActiveCases": 534,
    "SeriousCritical": 8,
    "TotCasesPer1Mpop": 476,
    "DeathsPer1Mpop": 62,
    "TotalTests": 352546,
    "TestsPer1Mpop": 36504,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Malawi",
    "Continent": "Africa",
    "Population": 19174839,
    "TotalCases": 4491,
    "NewCases": "",
    "TotalDeaths": 137,
    "NewDeaths": "",
    "TotalRecovered": 2137,
    "NewRecovered": "",
    "ActiveCases": 2217,
    "SeriousCritical": 4,
    "TotCasesPer1Mpop": 234,
    "DeathsPer1Mpop": 7,
    "TotalTests": 33466,
    "TestsPer1Mpop": 1745,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Zimbabwe",
    "Continent": "Africa",
    "Population": 14883803,
    "TotalCases": 4339,
    "NewCases": "",
    "TotalDeaths": 84,
    "NewDeaths": "",
    "TotalRecovered": 1264,
    "NewRecovered": "",
    "ActiveCases": 2991,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 292,
    "DeathsPer1Mpop": 6,
    "TotalTests": 140421,
    "TestsPer1Mpop": 9434,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Nicaragua",
    "Continent": "North America",
    "Population": 6632263,
    "TotalCases": 3902,
    "NewCases": "",
    "TotalDeaths": 123,
    "NewDeaths": "",
    "TotalRecovered": 2913,
    "NewRecovered": "",
    "ActiveCases": 866,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 588,
    "DeathsPer1Mpop": 19,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Hong Kong",
    "Continent": "Asia",
    "Population": 7503041,
    "TotalCases": 3850,
    "NewCases": "",
    "TotalDeaths": 46,
    "NewDeaths": "",
    "TotalRecovered": 2458,
    "NewRecovered": "",
    "ActiveCases": 1346,
    "SeriousCritical": 39,
    "TotCasesPer1Mpop": 513,
    "DeathsPer1Mpop": 6,
    "TotalTests": 692430,
    "TestsPer1Mpop": 92287,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Congo",
    "Continent": "Africa",
    "Population": 5530506,
    "TotalCases": 3546,
    "NewCases": "",
    "TotalDeaths": 58,
    "NewDeaths": "",
    "TotalRecovered": 1589,
    "NewRecovered": "",
    "ActiveCases": 1899,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 641,
    "DeathsPer1Mpop": 10,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Montenegro",
    "Continent": "Europe",
    "Population": 628074,
    "TotalCases": 3480,
    "NewCases": "",
    "TotalDeaths": 60,
    "NewDeaths": "",
    "TotalRecovered": 2178,
    "NewRecovered": "",
    "ActiveCases": 1242,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 5541,
    "DeathsPer1Mpop": 96,
    "TotalTests": 38427,
    "TestsPer1Mpop": 61182,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Thailand",
    "Continent": "Asia",
    "Population": 69817894,
    "TotalCases": 3330,
    "NewCases": "",
    "TotalDeaths": 58,
    "NewDeaths": "",
    "TotalRecovered": 3148,
    "NewRecovered": "",
    "ActiveCases": 124,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 48,
    "DeathsPer1Mpop": 0.8,
    "TotalTests": 749213,
    "TestsPer1Mpop": 10731,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Somalia",
    "Continent": "Africa",
    "Population": 15933012,
    "TotalCases": 3227,
    "NewCases": "",
    "TotalDeaths": 93,
    "NewDeaths": "",
    "TotalRecovered": 1728,
    "NewRecovered": "",
    "ActiveCases": 1406,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 203,
    "DeathsPer1Mpop": 6,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Mayotte",
    "Continent": "Africa",
    "Population": 273419,
    "TotalCases": 3042,
    "NewCases": "",
    "TotalDeaths": 39,
    "NewDeaths": "",
    "TotalRecovered": 2738,
    "NewRecovered": "",
    "ActiveCases": 265,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 11126,
    "DeathsPer1Mpop": 143,
    "TotalTests": 13000,
    "TestsPer1Mpop": 47546,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Eswatini",
    "Continent": "Africa",
    "Population": 1161348,
    "TotalCases": 2968,
    "NewCases": "",
    "TotalDeaths": 55,
    "NewDeaths": "",
    "TotalRecovered": 1476,
    "NewRecovered": "",
    "ActiveCases": 1437,
    "SeriousCritical": 5,
    "TotCasesPer1Mpop": 2556,
    "DeathsPer1Mpop": 47,
    "TotalTests": 20784,
    "TestsPer1Mpop": 17896,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Sri Lanka",
    "Continent": "Asia",
    "Population": 21422362,
    "TotalCases": 2839,
    "NewCases": "",
    "TotalDeaths": 11,
    "NewDeaths": "",
    "TotalRecovered": 2541,
    "NewRecovered": "",
    "ActiveCases": 287,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 133,
    "DeathsPer1Mpop": 0.5,
    "TotalTests": 166737,
    "TestsPer1Mpop": 7783,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Cuba",
    "Continent": "North America",
    "Population": 11325899,
    "TotalCases": 2775,
    "NewCases": "",
    "TotalDeaths": 88,
    "NewDeaths": "",
    "TotalRecovered": 2409,
    "NewRecovered": "",
    "ActiveCases": 278,
    "SeriousCritical": 4,
    "TotCasesPer1Mpop": 245,
    "DeathsPer1Mpop": 8,
    "TotalTests": 285471,
    "TestsPer1Mpop": 25205,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Cabo Verde",
    "Continent": "Africa",
    "Population": 556581,
    "TotalCases": 2734,
    "NewCases": "",
    "TotalDeaths": 27,
    "NewDeaths": "",
    "TotalRecovered": 2010,
    "NewRecovered": "",
    "ActiveCases": 697,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 4912,
    "DeathsPer1Mpop": 49,
    "TotalTests": 61633,
    "TestsPer1Mpop": 110735,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Namibia",
    "Continent": "Africa",
    "Population": 2545264,
    "TotalCases": 2652,
    "NewCases": "",
    "TotalDeaths": 15,
    "NewDeaths": "",
    "TotalRecovered": 563,
    "NewRecovered": "",
    "ActiveCases": 2074,
    "SeriousCritical": 24,
    "TotCasesPer1Mpop": 1042,
    "DeathsPer1Mpop": 6,
    "TotalTests": 29233,
    "TestsPer1Mpop": 11485,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Mali",
    "Continent": "Africa",
    "Population": 20302901,
    "TotalCases": 2552,
    "NewCases": "",
    "TotalDeaths": 124,
    "NewDeaths": "",
    "TotalRecovered": 1954,
    "NewRecovered": "",
    "ActiveCases": 474,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 126,
    "DeathsPer1Mpop": 6,
    "TotalTests": 25152,
    "TestsPer1Mpop": 1239,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Slovakia",
    "Continent": "Europe",
    "Population": 5459915,
    "TotalCases": 2480,
    "NewCases": "",
    "TotalDeaths": 29,
    "NewDeaths": "",
    "TotalRecovered": 1824,
    "NewRecovered": "",
    "ActiveCases": 627,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 454,
    "DeathsPer1Mpop": 5,
    "TotalTests": 272322,
    "TestsPer1Mpop": 49877,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "South Sudan",
    "Continent": "Africa",
    "Population": 11206572,
    "TotalCases": 2450,
    "NewCases": "",
    "TotalDeaths": 47,
    "NewDeaths": "",
    "TotalRecovered": 1175,
    "NewRecovered": "",
    "ActiveCases": 1228,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 219,
    "DeathsPer1Mpop": 4,
    "TotalTests": 12044,
    "TestsPer1Mpop": 1075,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Slovenia",
    "Continent": "Europe",
    "Population": 2078968,
    "TotalCases": 2223,
    "NewCases": "",
    "TotalDeaths": 125,
    "NewDeaths": "",
    "TotalRecovered": 1909,
    "NewRecovered": "",
    "ActiveCases": 189,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 1069,
    "DeathsPer1Mpop": 60,
    "TotalTests": 135702,
    "TestsPer1Mpop": 65274,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Lithuania",
    "Continent": "Europe",
    "Population": 2718121,
    "TotalCases": 2171,
    "NewCases": "",
    "TotalDeaths": 81,
    "NewDeaths": "",
    "TotalRecovered": 1656,
    "NewRecovered": "",
    "ActiveCases": 434,
    "SeriousCritical": 6,
    "TotCasesPer1Mpop": 799,
    "DeathsPer1Mpop": 30,
    "TotalTests": 540784,
    "TestsPer1Mpop": 198955,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Estonia",
    "Continent": "Europe",
    "Population": 1326627,
    "TotalCases": 2124,
    "NewCases": "",
    "TotalDeaths": 63,
    "NewDeaths": "",
    "TotalRecovered": 1954,
    "NewRecovered": "",
    "ActiveCases": 107,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 1601,
    "DeathsPer1Mpop": 47,
    "TotalTests": 122880,
    "TestsPer1Mpop": 92626,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Mozambique",
    "Continent": "Africa",
    "Population": 31333962,
    "TotalCases": 2120,
    "NewCases": "",
    "TotalDeaths": 15,
    "NewDeaths": "",
    "TotalRecovered": 795,
    "NewRecovered": "",
    "ActiveCases": 1310,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 68,
    "DeathsPer1Mpop": 0.5,
    "TotalTests": 65151,
    "TestsPer1Mpop": 2079,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Rwanda",
    "Continent": "Africa",
    "Population": 12981546,
    "TotalCases": 2111,
    "NewCases": "",
    "TotalDeaths": 5,
    "NewDeaths": "",
    "TotalRecovered": 1258,
    "NewRecovered": "",
    "ActiveCases": 848,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 163,
    "DeathsPer1Mpop": 0.4,
    "TotalTests": 286251,
    "TestsPer1Mpop": 22051,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Suriname",
    "Continent": "South America",
    "Population": 587154,
    "TotalCases": 2096,
    "NewCases": "",
    "TotalDeaths": 29,
    "NewDeaths": "",
    "TotalRecovered": 1446,
    "NewRecovered": "",
    "ActiveCases": 621,
    "SeriousCritical": 9,
    "TotCasesPer1Mpop": 3570,
    "DeathsPer1Mpop": 49,
    "TotalTests": 2785,
    "TestsPer1Mpop": 4743,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Guinea-Bissau",
    "Continent": "Africa",
    "Population": 1972277,
    "TotalCases": 2032,
    "NewCases": "",
    "TotalDeaths": 27,
    "NewDeaths": "",
    "TotalRecovered": 944,
    "NewRecovered": "",
    "ActiveCases": 1061,
    "SeriousCritical": 5,
    "TotCasesPer1Mpop": 1030,
    "DeathsPer1Mpop": 14,
    "TotalTests": 1500,
    "TestsPer1Mpop": 761,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Benin",
    "Continent": "Africa",
    "Population": 12151976,
    "TotalCases": 1936,
    "NewCases": "",
    "TotalDeaths": 38,
    "NewDeaths": "",
    "TotalRecovered": 1600,
    "NewRecovered": "",
    "ActiveCases": 298,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 159,
    "DeathsPer1Mpop": 3,
    "TotalTests": 93677,
    "TestsPer1Mpop": 7709,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Iceland",
    "Continent": "Europe",
    "Population": 341465,
    "TotalCases": 1930,
    "NewCases": "",
    "TotalDeaths": 10,
    "NewDeaths": "",
    "TotalRecovered": 1825,
    "NewRecovered": "",
    "ActiveCases": 95,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 5652,
    "DeathsPer1Mpop": 29,
    "TotalTests": 149693,
    "TestsPer1Mpop": 438385,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Sierra Leone",
    "Continent": "Africa",
    "Population": 7992169,
    "TotalCases": 1877,
    "NewCases": "",
    "TotalDeaths": 67,
    "NewDeaths": "",
    "TotalRecovered": 1427,
    "NewRecovered": "",
    "ActiveCases": 383,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 235,
    "DeathsPer1Mpop": 8,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Yemen",
    "Continent": "Asia",
    "Population": 29886897,
    "TotalCases": 1768,
    "NewCases": "",
    "TotalDeaths": 508,
    "NewDeaths": "",
    "TotalRecovered": 898,
    "NewRecovered": "",
    "ActiveCases": 362,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 59,
    "DeathsPer1Mpop": 17,
    "TotalTests": 120,
    "TestsPer1Mpop": 4,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Tunisia",
    "Continent": "Africa",
    "Population": 11830801,
    "TotalCases": 1642,
    "NewCases": "",
    "TotalDeaths": 51,
    "NewDeaths": "",
    "TotalRecovered": 1241,
    "NewRecovered": "",
    "ActiveCases": 350,
    "SeriousCritical": 9,
    "TotCasesPer1Mpop": 139,
    "DeathsPer1Mpop": 4,
    "TotalTests": 100298,
    "TestsPer1Mpop": 8478,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "New Zealand",
    "Continent": "Australia/Oceania",
    "Population": 5002100,
    "TotalCases": 1569,
    "NewCases": "",
    "TotalDeaths": 22,
    "NewDeaths": "",
    "TotalRecovered": 1524,
    "NewRecovered": "",
    "ActiveCases": 23,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 314,
    "DeathsPer1Mpop": 4,
    "TotalTests": 486943,
    "TestsPer1Mpop": 97348,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Angola",
    "Continent": "Africa",
    "Population": 32956300,
    "TotalCases": 1483,
    "NewCases": "",
    "TotalDeaths": 64,
    "NewDeaths": "",
    "TotalRecovered": 520,
    "NewRecovered": "",
    "ActiveCases": 899,
    "SeriousCritical": 20,
    "TotCasesPer1Mpop": 45,
    "DeathsPer1Mpop": 2,
    "TotalTests": 64747,
    "TestsPer1Mpop": 1965,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Uruguay",
    "Continent": "South America",
    "Population": 3474956,
    "TotalCases": 1318,
    "NewCases": "",
    "TotalDeaths": 37,
    "NewDeaths": "",
    "TotalRecovered": 1079,
    "NewRecovered": "",
    "ActiveCases": 202,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 379,
    "DeathsPer1Mpop": 11,
    "TotalTests": 126956,
    "TestsPer1Mpop": 36535,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Latvia",
    "Continent": "Europe",
    "Population": 1883936,
    "TotalCases": 1275,
    "NewCases": "",
    "TotalDeaths": 32,
    "NewDeaths": "",
    "TotalRecovered": 1070,
    "NewRecovered": "",
    "ActiveCases": 173,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 677,
    "DeathsPer1Mpop": 17,
    "TotalTests": 207909,
    "TestsPer1Mpop": 110359,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Jordan",
    "Continent": "Asia",
    "Population": 10213138,
    "TotalCases": 1232,
    "NewCases": "",
    "TotalDeaths": 11,
    "NewDeaths": "",
    "TotalRecovered": 1171,
    "NewRecovered": "",
    "ActiveCases": 50,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 121,
    "DeathsPer1Mpop": 1,
    "TotalTests": 628745,
    "TestsPer1Mpop": 61562,
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Liberia",
    "Continent": "Africa",
    "Population": 5068618,
    "TotalCases": 1224,
    "NewCases": "",
    "TotalDeaths": 78,
    "NewDeaths": "",
    "TotalRecovered": 705,
    "NewRecovered": "",
    "ActiveCases": 441,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 241,
    "DeathsPer1Mpop": 15,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Uganda",
    "Continent": "Africa",
    "Population": 45867852,
    "TotalCases": 1223,
    "NewCases": "",
    "TotalDeaths": 5,
    "NewDeaths": "",
    "TotalRecovered": 1102,
    "NewRecovered": "",
    "ActiveCases": 116,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 27,
    "DeathsPer1Mpop": 0.1,
    "TotalTests": 288367,
    "TestsPer1Mpop": 6287,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Cyprus",
    "Continent": "Asia",
    "Population": 1208238,
    "TotalCases": 1208,
    "NewCases": "",
    "TotalDeaths": 19,
    "NewDeaths": "",
    "TotalRecovered": 856,
    "NewRecovered": "",
    "ActiveCases": 333,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 1000,
    "DeathsPer1Mpop": 16,
    "TotalTests": 216597,
    "TestsPer1Mpop": 179267,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Georgia",
    "Continent": "Asia",
    "Population": 3988368,
    "TotalCases": 1206,
    "NewCases": "",
    "TotalDeaths": 17,
    "NewDeaths": "",
    "TotalRecovered": 987,
    "NewRecovered": "",
    "ActiveCases": 202,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 302,
    "DeathsPer1Mpop": 4,
    "TotalTests": 240473,
    "TestsPer1Mpop": 60294,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Burkina Faso",
    "Continent": "Africa",
    "Population": 20954852,
    "TotalCases": 1158,
    "NewCases": "",
    "TotalDeaths": 54,
    "NewDeaths": "",
    "TotalRecovered": 961,
    "NewRecovered": "",
    "ActiveCases": 143,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 55,
    "DeathsPer1Mpop": 3,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Niger",
    "Continent": "Africa",
    "Population": 24281433,
    "TotalCases": 1153,
    "NewCases": "",
    "TotalDeaths": 69,
    "NewDeaths": "",
    "TotalRecovered": 1057,
    "NewRecovered": "",
    "ActiveCases": 27,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 47,
    "DeathsPer1Mpop": 3,
    "TotalTests": 9052,
    "TestsPer1Mpop": 373,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Togo",
    "Continent": "Africa",
    "Population": 8296582,
    "TotalCases": 1012,
    "NewCases": "",
    "TotalDeaths": 22,
    "NewDeaths": "",
    "TotalRecovered": 697,
    "NewRecovered": "",
    "ActiveCases": 293,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 122,
    "DeathsPer1Mpop": 3,
    "TotalTests": 45767,
    "TestsPer1Mpop": 5516,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Syria",
    "Continent": "Asia",
    "Population": 17539600,
    "TotalCases": 999,
    "NewCases": "",
    "TotalDeaths": 48,
    "NewDeaths": "",
    "TotalRecovered": 311,
    "NewRecovered": "",
    "ActiveCases": 640,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 57,
    "DeathsPer1Mpop": 3,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "EasternMediterranean"
  },
  {
    "CountryRegion": "Jamaica",
    "Continent": "North America",
    "Population": 2962478,
    "TotalCases": 958,
    "NewCases": 30,
    "TotalDeaths": 12,
    "NewDeaths": "",
    "TotalRecovered": 745,
    "NewRecovered": "",
    "ActiveCases": 201,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 323,
    "DeathsPer1Mpop": 4,
    "TotalTests": 41840,
    "TestsPer1Mpop": 14123,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Malta",
    "Continent": "Europe",
    "Population": 441663,
    "TotalCases": 946,
    "NewCases": "",
    "TotalDeaths": 9,
    "NewDeaths": "",
    "TotalRecovered": 670,
    "NewRecovered": "",
    "ActiveCases": 267,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 2142,
    "DeathsPer1Mpop": 20,
    "TotalTests": 136713,
    "TestsPer1Mpop": 309541,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Andorra",
    "Continent": "Europe",
    "Population": 77278,
    "TotalCases": 944,
    "NewCases": "",
    "TotalDeaths": 52,
    "NewDeaths": "",
    "TotalRecovered": 828,
    "NewRecovered": "",
    "ActiveCases": 64,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 12216,
    "DeathsPer1Mpop": 673,
    "TotalTests": 3750,
    "TestsPer1Mpop": 48526,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Chad",
    "Continent": "Africa",
    "Population": 16467965,
    "TotalCases": 942,
    "NewCases": "",
    "TotalDeaths": 76,
    "NewDeaths": "",
    "TotalRecovered": 838,
    "NewRecovered": "",
    "ActiveCases": 28,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 57,
    "DeathsPer1Mpop": 5,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Gambia",
    "Continent": "Africa",
    "Population": 2422754,
    "TotalCases": 935,
    "NewCases": "",
    "TotalDeaths": 16,
    "NewDeaths": "",
    "TotalRecovered": 136,
    "NewRecovered": "",
    "ActiveCases": 783,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 386,
    "DeathsPer1Mpop": 7,
    "TotalTests": 5183,
    "TestsPer1Mpop": 2139,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Sao Tome and Principe",
    "Continent": "Africa",
    "Population": 219544,
    "TotalCases": 878,
    "NewCases": "",
    "TotalDeaths": 15,
    "NewDeaths": "",
    "TotalRecovered": 797,
    "NewRecovered": "",
    "ActiveCases": 66,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3999,
    "DeathsPer1Mpop": 68,
    "TotalTests": 3079,
    "TestsPer1Mpop": 14025,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Botswana",
    "Continent": "Africa",
    "Population": 2356075,
    "TotalCases": 804,
    "NewCases": "",
    "TotalDeaths": 2,
    "NewDeaths": "",
    "TotalRecovered": 63,
    "NewRecovered": "",
    "ActiveCases": 739,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 341,
    "DeathsPer1Mpop": 0.8,
    "TotalTests": 68423,
    "TestsPer1Mpop": 29041,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Bahamas",
    "Continent": "North America",
    "Population": 393616,
    "TotalCases": 761,
    "NewCases": "",
    "TotalDeaths": 14,
    "NewDeaths": "",
    "TotalRecovered": 91,
    "NewRecovered": "",
    "ActiveCases": 656,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 1933,
    "DeathsPer1Mpop": 36,
    "TotalTests": 4814,
    "TestsPer1Mpop": 12230,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Vietnam",
    "Continent": "Asia",
    "Population": 97425470,
    "TotalCases": 747,
    "NewCases": "",
    "TotalDeaths": 10,
    "NewDeaths": "",
    "TotalRecovered": 392,
    "NewRecovered": "",
    "ActiveCases": 345,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 8,
    "DeathsPer1Mpop": 0.1,
    "TotalTests": 482456,
    "TestsPer1Mpop": 4952,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Lesotho",
    "Continent": "Africa",
    "Population": 2143943,
    "TotalCases": 742,
    "NewCases": "",
    "TotalDeaths": 23,
    "NewDeaths": "",
    "TotalRecovered": 175,
    "NewRecovered": "",
    "ActiveCases": 544,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 346,
    "DeathsPer1Mpop": 11,
    "TotalTests": 8771,
    "TestsPer1Mpop": 4091,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Diamond Princess",
    "Continent": "",
    "Population": "",
    "TotalCases": 712,
    "NewCases": "",
    "TotalDeaths": 13,
    "NewDeaths": "",
    "TotalRecovered": 651,
    "NewRecovered": "",
    "ActiveCases": 48,
    "SeriousCritical": 4,
    "TotCasesPer1Mpop": "",
    "DeathsPer1Mpop": "",
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": ""
  },
  {
    "CountryRegion": "San Marino",
    "Continent": "Europe",
    "Population": 33938,
    "TotalCases": 699,
    "NewCases": "",
    "TotalDeaths": 42,
    "NewDeaths": "",
    "TotalRecovered": 657,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 20596,
    "DeathsPer1Mpop": 1238,
    "TotalTests": 6068,
    "TestsPer1Mpop": 178797,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Réunion",
    "Continent": "Africa",
    "Population": 895952,
    "TotalCases": 671,
    "NewCases": "",
    "TotalDeaths": 5,
    "NewDeaths": "",
    "TotalRecovered": 592,
    "NewRecovered": "",
    "ActiveCases": 74,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 749,
    "DeathsPer1Mpop": 6,
    "TotalTests": 35419,
    "TestsPer1Mpop": 39532,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Channel Islands",
    "Continent": "Europe",
    "Population": 174022,
    "TotalCases": 597,
    "NewCases": "",
    "TotalDeaths": 47,
    "NewDeaths": "",
    "TotalRecovered": 533,
    "NewRecovered": "",
    "ActiveCases": 17,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3431,
    "DeathsPer1Mpop": 270,
    "TotalTests": 30721,
    "TestsPer1Mpop": 176535,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Guyana",
    "Continent": "South America",
    "Population": 786936,
    "TotalCases": 538,
    "NewCases": "",
    "TotalDeaths": 22,
    "NewDeaths": "",
    "TotalRecovered": 189,
    "NewRecovered": "",
    "ActiveCases": 327,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 684,
    "DeathsPer1Mpop": 28,
    "TotalTests": 5165,
    "TestsPer1Mpop": 6563,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Tanzania",
    "Continent": "Africa",
    "Population": 59886383,
    "TotalCases": 509,
    "NewCases": "",
    "TotalDeaths": 21,
    "NewDeaths": "",
    "TotalRecovered": 183,
    "NewRecovered": "",
    "ActiveCases": 305,
    "SeriousCritical": 7,
    "TotCasesPer1Mpop": 8,
    "DeathsPer1Mpop": 0.4,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Taiwan",
    "Continent": "Asia",
    "Population": 23821199,
    "TotalCases": 477,
    "NewCases": "",
    "TotalDeaths": 7,
    "NewDeaths": "",
    "TotalRecovered": 443,
    "NewRecovered": "",
    "ActiveCases": 27,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 20,
    "DeathsPer1Mpop": 0.3,
    "TotalTests": 82737,
    "TestsPer1Mpop": 3473,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Comoros",
    "Continent": "Africa",
    "Population": 871326,
    "TotalCases": 396,
    "NewCases": "",
    "TotalDeaths": 7,
    "NewDeaths": "",
    "TotalRecovered": 340,
    "NewRecovered": "",
    "ActiveCases": 49,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 454,
    "DeathsPer1Mpop": 8,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Burundi",
    "Continent": "Africa",
    "Population": 11922216,
    "TotalCases": 395,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 304,
    "NewRecovered": "",
    "ActiveCases": 90,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 33,
    "DeathsPer1Mpop": 0.08,
    "TotalTests": 15614,
    "TestsPer1Mpop": 1310,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Myanmar",
    "Continent": "Asia",
    "Population": 54446389,
    "TotalCases": 357,
    "NewCases": "",
    "TotalDeaths": 6,
    "NewDeaths": "",
    "TotalRecovered": 308,
    "NewRecovered": "",
    "ActiveCases": 43,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 7,
    "DeathsPer1Mpop": 0.1,
    "TotalTests": 122290,
    "TestsPer1Mpop": 2246,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Mauritius",
    "Continent": "Africa",
    "Population": 1271985,
    "TotalCases": 344,
    "NewCases": "",
    "TotalDeaths": 10,
    "NewDeaths": "",
    "TotalRecovered": 334,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 270,
    "DeathsPer1Mpop": 8,
    "TotalTests": 205285,
    "TestsPer1Mpop": 161389,
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Isle of Man",
    "Continent": "Europe",
    "Population": 85078,
    "TotalCases": 336,
    "NewCases": "",
    "TotalDeaths": 24,
    "NewDeaths": "",
    "TotalRecovered": 312,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3949,
    "DeathsPer1Mpop": 282,
    "TotalTests": 8627,
    "TestsPer1Mpop": 101401,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Mongolia",
    "Continent": "Asia",
    "Population": 3283344,
    "TotalCases": 293,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 260,
    "NewRecovered": "",
    "ActiveCases": 33,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 89,
    "DeathsPer1Mpop": "",
    "TotalTests": 38334,
    "TestsPer1Mpop": 11675,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Eritrea",
    "Continent": "Africa",
    "Population": 3551175,
    "TotalCases": 282,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 225,
    "NewRecovered": "",
    "ActiveCases": 57,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 79,
    "DeathsPer1Mpop": "",
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Guadeloupe",
    "Continent": "North America",
    "Population": 400131,
    "TotalCases": 279,
    "NewCases": "",
    "TotalDeaths": 14,
    "NewDeaths": "",
    "TotalRecovered": 179,
    "NewRecovered": "",
    "ActiveCases": 86,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 697,
    "DeathsPer1Mpop": 35,
    "TotalTests": 18476,
    "TestsPer1Mpop": 46175,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Martinique",
    "Continent": "North America",
    "Population": 375235,
    "TotalCases": 276,
    "NewCases": "",
    "TotalDeaths": 15,
    "NewDeaths": "",
    "TotalRecovered": 98,
    "NewRecovered": "",
    "ActiveCases": 163,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 736,
    "DeathsPer1Mpop": 40,
    "TotalTests": 12227,
    "TestsPer1Mpop": 32585,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Faeroe Islands",
    "Continent": "Europe",
    "Population": 48882,
    "TotalCases": 266,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 192,
    "NewRecovered": "",
    "ActiveCases": 74,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 5442,
    "DeathsPer1Mpop": "",
    "TotalTests": 43045,
    "TestsPer1Mpop": 880590,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Aruba",
    "Continent": "North America",
    "Population": 106812,
    "TotalCases": 263,
    "NewCases": "",
    "TotalDeaths": 3,
    "NewDeaths": "",
    "TotalRecovered": 114,
    "NewRecovered": "",
    "ActiveCases": 146,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 2462,
    "DeathsPer1Mpop": 28,
    "TotalTests": 14047,
    "TestsPer1Mpop": 131511,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Cambodia",
    "Continent": "Asia",
    "Population": 16741375,
    "TotalCases": 243,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 210,
    "NewRecovered": "",
    "ActiveCases": 33,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 15,
    "DeathsPer1Mpop": "",
    "TotalTests": 67807,
    "TestsPer1Mpop": 4050,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Trinidad and Tobago",
    "Continent": "North America",
    "Population": 1399950,
    "TotalCases": 210,
    "NewCases": "",
    "TotalDeaths": 8,
    "NewDeaths": "",
    "TotalRecovered": 135,
    "NewRecovered": "",
    "ActiveCases": 67,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 150,
    "DeathsPer1Mpop": 6,
    "TotalTests": 9559,
    "TestsPer1Mpop": 6828,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Cayman Islands",
    "Continent": "North America",
    "Population": 65798,
    "TotalCases": 203,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 202,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3085,
    "DeathsPer1Mpop": 15,
    "TotalTests": 31108,
    "TestsPer1Mpop": 472780,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Gibraltar",
    "Continent": "Europe",
    "Population": 33690,
    "TotalCases": 190,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 184,
    "NewRecovered": "",
    "ActiveCases": 6,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 5640,
    "DeathsPer1Mpop": "",
    "TotalTests": 23063,
    "TestsPer1Mpop": 684565,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Papua New Guinea",
    "Continent": "Australia/Oceania",
    "Population": 8963009,
    "TotalCases": 163,
    "NewCases": "",
    "TotalDeaths": 3,
    "NewDeaths": "",
    "TotalRecovered": 53,
    "NewRecovered": "",
    "ActiveCases": 107,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 18,
    "DeathsPer1Mpop": 0.3,
    "TotalTests": 10808,
    "TestsPer1Mpop": 1206,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Sint Maarten",
    "Continent": "North America",
    "Population": 42924,
    "TotalCases": 160,
    "NewCases": "",
    "TotalDeaths": 16,
    "NewDeaths": "",
    "TotalRecovered": 64,
    "NewRecovered": "",
    "ActiveCases": 80,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 3728,
    "DeathsPer1Mpop": 373,
    "TotalTests": 1115,
    "TestsPer1Mpop": 25976,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Bermuda",
    "Continent": "North America",
    "Population": 62254,
    "TotalCases": 157,
    "NewCases": "",
    "TotalDeaths": 9,
    "NewDeaths": "",
    "TotalRecovered": 144,
    "NewRecovered": "",
    "ActiveCases": 4,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 2522,
    "DeathsPer1Mpop": 145,
    "TotalTests": 26352,
    "TestsPer1Mpop": 423298,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Brunei",
    "Continent": "Asia",
    "Population": 437893,
    "TotalCases": 141,
    "NewCases": "",
    "TotalDeaths": 3,
    "NewDeaths": "",
    "TotalRecovered": 138,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 322,
    "DeathsPer1Mpop": 7,
    "TotalTests": 41148,
    "TestsPer1Mpop": 93968,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Barbados",
    "Continent": "North America",
    "Population": 287411,
    "TotalCases": 133,
    "NewCases": "",
    "TotalDeaths": 7,
    "NewDeaths": "",
    "TotalRecovered": 100,
    "NewRecovered": "",
    "ActiveCases": 26,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 463,
    "DeathsPer1Mpop": 24,
    "TotalTests": 12233,
    "TestsPer1Mpop": 42563,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Turks and Caicos",
    "Continent": "North America",
    "Population": 38768,
    "TotalCases": 129,
    "NewCases": "",
    "TotalDeaths": 2,
    "NewDeaths": "",
    "TotalRecovered": 39,
    "NewRecovered": "",
    "ActiveCases": 88,
    "SeriousCritical": 3,
    "TotCasesPer1Mpop": 3327,
    "DeathsPer1Mpop": 52,
    "TotalTests": 1252,
    "TestsPer1Mpop": 32295,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Seychelles",
    "Continent": "Africa",
    "Population": 98408,
    "TotalCases": 126,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 124,
    "NewRecovered": "",
    "ActiveCases": 2,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 1280,
    "DeathsPer1Mpop": "",
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  },
  {
    "CountryRegion": "Monaco",
    "Continent": "Europe",
    "Population": 39270,
    "TotalCases": 125,
    "NewCases": "",
    "TotalDeaths": 4,
    "NewDeaths": "",
    "TotalRecovered": 105,
    "NewRecovered": "",
    "ActiveCases": 16,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 3183,
    "DeathsPer1Mpop": 102,
    "TotalTests": 38209,
    "TestsPer1Mpop": 972982,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Bhutan",
    "Continent": "Asia",
    "Population": 772443,
    "TotalCases": 105,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 93,
    "NewRecovered": "",
    "ActiveCases": 12,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 136,
    "DeathsPer1Mpop": "",
    "TotalTests": 54589,
    "TestsPer1Mpop": 70671,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Antigua and Barbuda",
    "Continent": "North America",
    "Population": 98010,
    "TotalCases": 92,
    "NewCases": "",
    "TotalDeaths": 3,
    "NewDeaths": "",
    "TotalRecovered": 76,
    "NewRecovered": "",
    "ActiveCases": 13,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 939,
    "DeathsPer1Mpop": 31,
    "TotalTests": 1500,
    "TestsPer1Mpop": 15305,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Liechtenstein",
    "Continent": "Europe",
    "Population": 38139,
    "TotalCases": 89,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 85,
    "NewRecovered": "",
    "ActiveCases": 3,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 2334,
    "DeathsPer1Mpop": 26,
    "TotalTests": 900,
    "TestsPer1Mpop": 23598,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Belize",
    "Continent": "North America",
    "Population": 398312,
    "TotalCases": 86,
    "NewCases": "",
    "TotalDeaths": 2,
    "NewDeaths": "",
    "TotalRecovered": 31,
    "NewRecovered": "",
    "ActiveCases": 53,
    "SeriousCritical": 2,
    "TotCasesPer1Mpop": 216,
    "DeathsPer1Mpop": 5,
    "TotalTests": 3679,
    "TestsPer1Mpop": 9236,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "French Polynesia",
    "Continent": "Australia/Oceania",
    "Population": 281072,
    "TotalCases": 64,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 62,
    "NewRecovered": "",
    "ActiveCases": 2,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 228,
    "DeathsPer1Mpop": "",
    "TotalTests": 5849,
    "TestsPer1Mpop": 20810,
    "WHORegion": ""
  },
  {
    "CountryRegion": "St. Vincent Grenadines",
    "Continent": "North America",
    "Population": 110976,
    "TotalCases": 56,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 46,
    "NewRecovered": "",
    "ActiveCases": 10,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 505,
    "DeathsPer1Mpop": "",
    "TotalTests": 2447,
    "TestsPer1Mpop": 22050,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Saint Martin",
    "Continent": "North America",
    "Population": 38729,
    "TotalCases": 53,
    "NewCases": "",
    "TotalDeaths": 3,
    "NewDeaths": "",
    "TotalRecovered": 41,
    "NewRecovered": "",
    "ActiveCases": 9,
    "SeriousCritical": 1,
    "TotCasesPer1Mpop": 1368,
    "DeathsPer1Mpop": 77,
    "TotalTests": 1183,
    "TestsPer1Mpop": 30546,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Macao",
    "Continent": "Asia",
    "Population": 650193,
    "TotalCases": 46,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 46,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 71,
    "DeathsPer1Mpop": "",
    "TotalTests": 4071,
    "TestsPer1Mpop": 6261,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Curaçao",
    "Continent": "North America",
    "Population": 164161,
    "TotalCases": 31,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 28,
    "NewRecovered": "",
    "ActiveCases": 2,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 189,
    "DeathsPer1Mpop": 6,
    "TotalTests": 1080,
    "TestsPer1Mpop": 6579,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Fiji",
    "Continent": "Australia/Oceania",
    "Population": 897095,
    "TotalCases": 27,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 18,
    "NewRecovered": "",
    "ActiveCases": 8,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 30,
    "DeathsPer1Mpop": 1,
    "TotalTests": 6693,
    "TestsPer1Mpop": 7461,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Saint Lucia",
    "Continent": "North America",
    "Population": 183712,
    "TotalCases": 25,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 24,
    "NewRecovered": "",
    "ActiveCases": 1,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 136,
    "DeathsPer1Mpop": "",
    "TotalTests": 3895,
    "TestsPer1Mpop": 21202,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Timor-Leste",
    "Continent": "Asia",
    "Population": 1320812,
    "TotalCases": 25,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 24,
    "NewRecovered": "",
    "ActiveCases": 1,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 19,
    "DeathsPer1Mpop": "",
    "TotalTests": 4238,
    "TestsPer1Mpop": 3209,
    "WHORegion": "South-EastAsia"
  },
  {
    "CountryRegion": "Grenada",
    "Continent": "North America",
    "Population": 112576,
    "TotalCases": 24,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 23,
    "NewRecovered": "",
    "ActiveCases": 1,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 213,
    "DeathsPer1Mpop": "",
    "TotalTests": 6252,
    "TestsPer1Mpop": 55536,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "New Caledonia",
    "Continent": "Australia/Oceania",
    "Population": 285769,
    "TotalCases": 22,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 22,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 77,
    "DeathsPer1Mpop": "",
    "TotalTests": 11099,
    "TestsPer1Mpop": 38839,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Laos",
    "Continent": "Asia",
    "Population": 7285750,
    "TotalCases": 20,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 19,
    "NewRecovered": "",
    "ActiveCases": 1,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3,
    "DeathsPer1Mpop": "",
    "TotalTests": 29374,
    "TestsPer1Mpop": 4032,
    "WHORegion": "WesternPacific"
  },
  {
    "CountryRegion": "Dominica",
    "Continent": "North America",
    "Population": 72004,
    "TotalCases": 18,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 18,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 250,
    "DeathsPer1Mpop": "",
    "TotalTests": 1005,
    "TestsPer1Mpop": 13958,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Saint Kitts and Nevis",
    "Continent": "North America",
    "Population": 53237,
    "TotalCases": 17,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 16,
    "NewRecovered": "",
    "ActiveCases": 1,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 319,
    "DeathsPer1Mpop": "",
    "TotalTests": 1146,
    "TestsPer1Mpop": 21526,
    "WHORegion": "Americas"
  },
  {
    "CountryRegion": "Greenland",
    "Continent": "North America",
    "Population": 56780,
    "TotalCases": 14,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 14,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 247,
    "DeathsPer1Mpop": "",
    "TotalTests": 5977,
    "TestsPer1Mpop": 105266,
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Montserrat",
    "Continent": "North America",
    "Population": 4992,
    "TotalCases": 13,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 10,
    "NewRecovered": "",
    "ActiveCases": 2,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 2604,
    "DeathsPer1Mpop": 200,
    "TotalTests": 61,
    "TestsPer1Mpop": 12220,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Caribbean Netherlands",
    "Continent": "North America",
    "Population": 26247,
    "TotalCases": 13,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 7,
    "NewRecovered": "",
    "ActiveCases": 6,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 495,
    "DeathsPer1Mpop": "",
    "TotalTests": 424,
    "TestsPer1Mpop": 16154,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Falkland Islands",
    "Continent": "South America",
    "Population": 3489,
    "TotalCases": 13,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 13,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 3726,
    "DeathsPer1Mpop": "",
    "TotalTests": 1816,
    "TestsPer1Mpop": 520493,
    "WHORegion": ""
  },
  {
    "CountryRegion": "Vatican City",
    "Continent": "Europe",
    "Population": 801,
    "TotalCases": 12,
    "NewCases": "",
    "TotalDeaths": "",
    "NewDeaths": "",
    "TotalRecovered": 12,
    "NewRecovered": "",
    "ActiveCases": 0,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 14981,
    "DeathsPer1Mpop": "",
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Europe"
  },
  {
    "CountryRegion": "Western Sahara",
    "Continent": "Africa",
    "Population": 598682,
    "TotalCases": 10,
    "NewCases": "",
    "TotalDeaths": 1,
    "NewDeaths": "",
    "TotalRecovered": 8,
    "NewRecovered": "",
    "ActiveCases": 1,
    "SeriousCritical": "",
    "TotCasesPer1Mpop": 17,
    "DeathsPer1Mpop": 2,
    "TotalTests": "",
    "TestsPer1Mpop": "",
    "WHORegion": "Africa"
  }
]